server:
  name: mygram
  env: local
  http:
    port: 9999
dataSource:
  mode: GORM
  migrate: true
  postgres:
    master:
      Host: localhost
      Port: 5432
      DBName: mygram
      Username: postgres
      Password: postgres
      maxIdleConnection: 10
      maxOpenConnection: 10
      maxIdleTime: 10