server:
  name: final-chapter2
  env: local
  http:
    port: 9090
dataSource:
  mode: GORM
  migrate: false
  postgres:
    master:
      Host: localhost
      Port: 5432
      DBName: final_project
      Username: postgres
      Password: postgres
      maxIdleConnection: 10
      maxOpenConnection: 10
      maxIdleTime: 10